### ISSUE TITLE
core dump from apache when deleting a plugin

### ISSUE THREAD

**Issue by gallak** [gallak/fusiondirectory-plugins-pluginsmanager#1]
When A remove a plugin like
`./fusiondirectory-plugin-manager --set-fd_home=/usr/local/share/fusiondirectory  --plugin-name=pluginsmanager --plugins-archive=/usr/local/src/gallak/ --remove-plugin`

plugin is successfully removed , but it generate a core dump from apache when try to access the fusiondirectory instance

**Comment by bilbo-the-hobbit** [comment]
@gallak 

in FusionDirectory you must be logged out before removing a plugin, because of the data stored into the session, if you try to use FusionDirectory in a old context you will have a crash in the browser and/or in apache

Cheers

**Comment by gallak** [comment]
you're right, logout login isn't enough, close browser or re open in private and FD come back
I close the issue thanks to your explanation and test
